### ISSUE TITLE
suggestion: failure for bad characters in passwords could be improved

### ISSUE THREAD

**Issue by markstos** [vitaly-t/connection-string#48]
Right now if there is an equal sign in a password, such as `password=`, the error message is:

       Error: Invalid port: "password". Valid port range is: [1...65535]

Since `=` is a reserved character according to RFC 3986, it should never appear unencoded in a password.  The rest of the reserved characters are:

      !	#	$	&	'	(	)	*	+	,	/	:	;	=	?	@	[	]

If any of these appear in a username or password or if `@` appears unencoded in the URI more than once, then an error could be thrown that explicitly express than an invalid character has been used.

Already three other issues have been opened by users who used reserved characters and then believed they had run into a bug in this library.  A clear error message would developers get back the right track faster-- even faster than searching through the issue tracker and reading the wiki to figure out what went wrong.

**Comment by vitaly-t** [comment]
This would imply parsing each section of the URL for the presence of invalid characters, which isn't possible, since this library supports fully optional syntax, which makes it easier to break syntax with invalid symbols.

But it should be sufficient that this library does list `=` = `%3D` [in its documentation](https://github.com/vitaly-t/connection-string/wiki/FAQ#how-to-use-special-symbols-for-user-name-or-password).

**Comment by vitaly-t** [comment]
Closing, because it cannot be improved, as was explained in the post above.
